#!/usr/bin/env node
/**
 * Reads `supabase status` output and writes .env.local automatically.
 * Run after `npm run db:start`.
 */

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')

const ROOT = path.resolve(__dirname, '..')
const ENV_FILE = path.join(ROOT, '.env.local')

console.log('📡 Reading Supabase status...')

let statusOutput
try {
  statusOutput = execSync('npx supabase status', { cwd: ROOT, encoding: 'utf8' })
} catch (err) {
  console.error('❌ Failed to run `supabase status`. Is the local stack running?')
  console.error('   Run: npm run db:start')
  process.exit(1)
}

function extract(label) {
  const match = statusOutput.match(new RegExp(`${label}:\\s*(\\S+)`))
  return match ? match[1] : null
}

const apiUrl        = extract('API URL')
const anonKey       = extract('anon key')
const serviceKey    = extract('service_role key')
const dbUrl         = extract('DB URL')
const studioUrl     = extract('Studio URL')
const inbucketUrl   = extract('Inbucket URL')

if (!apiUrl || !anonKey || !serviceKey) {
  console.error('❌ Could not parse Supabase status output. Raw output:')
  console.error(statusOutput)
  process.exit(1)
}

const envContent = `# Auto-generated by scripts/setup-env.js — ${new Date().toISOString()}
# Local Supabase — edit only if you know what you're doing

NEXT_PUBLIC_SUPABASE_URL=${apiUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceKey}
DATABASE_URL=${dbUrl || ''}

NEXT_PUBLIC_APP_URL=http://localhost:3000

# Local dev tools (not used by the app)
# Studio:  ${studioUrl || 'http://127.0.0.1:54323'}
# Inbucket: ${inbucketUrl || 'http://127.0.0.1:54324'}
`

fs.writeFileSync(ENV_FILE, envContent, 'utf8')
console.log(`✅ .env.local written successfully`)
console.log(`   API URL:     ${apiUrl}`)
console.log(`   Studio:      ${studioUrl || 'http://127.0.0.1:54323'}`)
console.log(`   Inbucket:    ${inbucketUrl || 'http://127.0.0.1:54324'}`)
console.log('')
console.log('🚀 Run: npm run dev')
